# example of github actions
name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: init
        run: cmake --preset DevDebug

      - name: build
        run: cmake --build --preset DevDebug
